### ISSUE TITLE
formitem 如何添加提示信息

### ISSUE THREAD

**Issue by tankjun** [tinper-bee/bee-form#10]
![qq 777](https://user-images.githubusercontent.com/32053876/32881430-312ea0c8-caec-11e7-95ac-09c4d732a778.png)

**Comment by lucian55** [comment]
1、使用 `inputAfter` ，然后再修改成你要的样式
2、在formItem后边加，再修改样式，

**Comment by tankjun** [comment]
恩，我在一个文本框输入文字，显示[object object]是什么问题

**Comment by liushaozhen** [comment]
微信   804199994  截图给我吧
