### ISSUE TITLE
默认带有提交按钮，实际业务需要定制提交按钮的位置 能否只对外提供提交按钮的回调函数

### ISSUE THREAD

**Issue by nclight** [tinper-bee/bee-form#6]
这个是默认的提供提交按钮
![selection_019](https://user-images.githubusercontent.com/32626678/32362072-5017f480-c0a1-11e7-8073-15e46041e1be.png)

实际业务按钮的位置需要定制， 如：
![selection_020](https://user-images.githubusercontent.com/32626678/32362097-80b7f64e-c0a1-11e7-9106-c624fbfe459e.png)

**Comment by lucian55** [comment]
这个功能正在加，加好以后和你说

**Comment by nclight** [comment]
加一下 微信 jiangjundetiaotiao  方便沟通一下 还有其他几个问题
