### ISSUE TITLE
form 表单提交按钮

### ISSUE THREAD

**Issue by tankjun** [tinper-bee/bee-form#7]
你好，能不能提供API支持能修改 提交按钮 的文字内容，或者我自定义一个按钮可以调用

submitCallBack={this.checkForm} 这个方法

**Comment by lucian55** [comment]
有这个功能，设置form的 showSubmit={false} 可以不使用form自带的提交按钮。
使用 设置form的 checkFormNow={true}  可以触发submitCallBack方法

**Comment by tankjun** [comment]
你好，submitCallBack方法何时触发呢，怎么触发？

**Comment by lucian55** [comment]
设置form的 checkFormNow={true} 就自动触发submitCallBack方法了

**Comment by tankjun** [comment]
现在有个问题，就是我加了校验，再没输入就触发了，就提示输入错误，点击了button 按钮又触发一次

**Comment by liushaozhen** [comment]
再没输入是啥意思。。。

**Comment by lucian55** [comment]
没明白你的意思

**Comment by tankjun** [comment]
我表单是在模态框里面， 模态框一打开就触发了submitCallBack提交方法，还没输入信息就触发

**Comment by lucian55** [comment]
你默认给checkFormNow是true？？？？

**Comment by tankjun** [comment]
恩，如果默认是false ，我自定义按钮如何改为true

**Comment by tankjun** [comment]
其实最简单的是能不能把提交按钮 提交两个字，换成我们业务自定义的

**Comment by lucian55** [comment]
默认是true就会触发。
checkFormNow={this.state.checkFormNow}
点击你自己提交按钮的时候，把state.checkFormNow更改为true即可

**Comment by lucian55** [comment]
“提交” 文字修改目前不支持。后续增加

**Comment by tankjun** [comment]
恩，好的，谢谢，我知道了
