### ISSUE TITLE
form表单的其他问题

### ISSUE THREAD

**Issue by yang123guo** [tinper-bee/bee-form#8]
### 需求

1、isrequire = {true}  代表必选，能不能给labName加一个class类名，好用来使我们加 * 或者其他的样式来标志，而不是自己再自定义类名

2、键盘时间 ，比如enter事件 (优先级低)

### 问题

1、现有数据data（是个对象，name和每个formItem匹配），回显的时候，能不能把data赋给form组件，让他自动匹配渲染。

**Comment by lucian55** [comment]
### 需求
1、目前支持此功能。可以给formItem增加 labelClassName=你想要的样式名
2、这个后续这边商量是否增加。如果你那边现在有这个需要，可以设置enter后出发form校验。checkFormNow={true}即可出发form校验
### 问题
1、这个后续这边商量是否增加

**Comment by yang123guo** [comment]
针对第一个问题，我的意思是  用户已经选了require 再加个labelClassName不是多余吗？

**Comment by lucian55** [comment]
label自身有className为u-label。  require加* 后续会暴露参数是否显示*
