### ISSUE TITLE
针对必填字段 添加必填标识的问题 

### ISSUE THREAD

**Issue by nclight** [tinper-bee/bee-form#9]
现在有需求，需要在必填的表单域文案位置标识必填 如图：

能否在FormItem 支持给label传className
![selection_039](https://user-images.githubusercontent.com/32626678/32817095-fee38af2-c9f6-11e7-8d2c-4488d66cc12a.png)

**Comment by lucian55** [comment]
目前支持给label传className， 也可以配置是否显示 * 
版本 1.0.11

|参数|说明|类型|默认值|
|:---|:-----|:----|:------|
|showMast|是否显示必输项的*|bool|false|
|labelClassName|输入框label标签的class|string|-|
